#!/usr/bin/env python3
"""Run Node's own test suite against this runtime.

Our suites test what I thought to test. Node's encode fifteen years of edge
cases other people hit, which is a different and better signal — so this exists
to be uncomfortable rather than to stay green.

    runtime/test/node-suite/run.py <node> [pattern ...]
    runtime/test/node-suite/run.py build/host-node/node fs net

A test is expected to fail when it exercises something this runtime does not
implement; those live in expected-failures.txt with a reason, and that file is a
machine-checked companion to runtime/docs/omissions.md. The run fails on a
result that disagrees with it in either direction — an unexpected failure, or a
test listed as failing that now passes.
"""

import argparse
import concurrent.futures
import pathlib
import shlex
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
TESTS = HERE / "node" / "parallel"
EXPECTED = HERE / "expected-failures.txt"

PASS, FAIL, SKIP, TIMEOUT = "pass", "fail", "skip", "timeout"


def load_expected():
    """name -> reason, for tests known not to pass here."""
    expected = {}

    if not EXPECTED.exists():
        return expected

    for line in EXPECTED.read_text().splitlines():
        line = line.strip()

        if not line or line.startswith("#"):
            continue

        name, _, reason = line.partition(" ")
        expected[name] = reason.strip()

    return expected


def run_one(node_cmd, test_path, timeout):
    try:
        proc = subprocess.run(
            node_cmd + [str(test_path)],
            cwd=str(TESTS),
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        return TIMEOUT, "timed out"

    output = proc.stdout + proc.stderr

    if "1..0 # Skipped" in output:
        return SKIP, output.strip().splitlines()[-1] if output.strip() else ""

    if proc.returncode == 0:
        return PASS, ""

    # The first interesting line is usually the assertion or the error.
    detail = ""

    for line in output.splitlines():
        stripped = line.strip()

        if stripped and not stripped.startswith("at "):
            detail = stripped
            break

    return FAIL, detail[:200]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("node", help="path to the runtime, or a wrapper command in quotes")
    ap.add_argument("patterns", nargs="*", default=["fs", "net"],
                    help="test-<pattern>-* groups to run (default: fs net)")
    ap.add_argument("--timeout", type=int, default=60)
    ap.add_argument("--jobs", type=int, default=8)
    ap.add_argument("--update-expected", action="store_true",
                    help="rewrite expected-failures.txt from this run")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    if not TESTS.is_dir():
        sys.exit("node-suite: run runtime/test/node-suite/fetch.sh first")

    # Tests run with their own directory as cwd, so a relative runtime path
    # would break. Resolve it here rather than making the caller do it.
    node_cmd = shlex.split(args.node)

    for i, part in enumerate(node_cmd):
        if pathlib.Path(part).exists():
            node_cmd[i] = str(pathlib.Path(part).resolve())
    patterns = args.patterns or ["fs", "net"]

    files = []

    for pattern in patterns:
        files.extend(sorted(TESTS.glob(f"test-{pattern}-*.js")))

    if not files:
        sys.exit(f"node-suite: no tests matched {patterns}")

    expected = load_expected()
    results = {}

    with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as pool:
        futures = {pool.submit(run_one, node_cmd, f, args.timeout): f for f in files}

        for future in concurrent.futures.as_completed(futures):
            path = futures[future]
            results[path.name] = future.result()

    counts = {PASS: 0, FAIL: 0, SKIP: 0, TIMEOUT: 0}

    for status, _ in results.values():
        counts[status] += 1

    failing = {n: d for n, (s, d) in sorted(results.items()) if s in (FAIL, TIMEOUT)}

    if args.update_expected:
        lines = [
            "# Node tests that do not pass on this runtime, with the reason.",
            "# Regenerated by run.py --update-expected; a machine-checked companion",
            "# to runtime/docs/omissions.md. Reasons are filled in by hand.",
            "",
        ]
        lines += [f"{name} {expected.get(name, '') or detail}" for name, detail in failing.items()]
        EXPECTED.write_text("\n".join(lines) + "\n")
        print(f"node-suite: wrote {len(failing)} entries to {EXPECTED.name}")

    unexpected_fail = [n for n in failing if n not in expected]
    unexpected_pass = [n for n, (s, _) in results.items() if s == PASS and n in expected]

    if not args.quiet:
        for name in unexpected_fail:
            print(f"  FAIL {name}: {failing[name]}")

        for name in unexpected_pass:
            print(f"  NOW PASSES (remove from expected-failures.txt): {name}")

    total = len(files)
    print(
        f"node-suite [{' '.join(patterns)}]: {counts[PASS]}/{total} pass, "
        f"{counts[FAIL]} fail, {counts[TIMEOUT]} timeout, {counts[SKIP]} skip "
        f"({len(expected)} expected failures)"
    )

    if args.update_expected:
        return 0

    if unexpected_fail or unexpected_pass:
        print(f"node-suite: {len(unexpected_fail)} unexpected failures, "
              f"{len(unexpected_pass)} newly passing")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
